import fs from 'node:fs';
import path from 'node:path';
import nock from 'nock';
import { afterAll, afterEach, beforeAll, describe, expect, it } from 'vitest';
import {
	inspectPlayerResponse,
	inspectPlayerResponseDebug,
} from '../lib/inspector';

const fixturesDir = path.join(process.cwd(), 'src', '__tests__', 'fixtures');
const VIDEO_ID = 'TESTVIDEOID';
const API_KEY = 'test-key';

const loadFixture = (name: string): string =>
	fs.readFileSync(path.join(fixturesDir, name), 'utf8');
const loadJsonFixture = (name: string): object =>
	JSON.parse(loadFixture(name)) as object;

const mockWatchPage = (body?: string) =>
	nock('https://www.youtube.com')
		.get('/watch')
		.query({ v: VIDEO_ID })
		.reply(200, body ?? loadFixture('watch.html'));

const mockPlayer = (body: object) =>
	nock('https://www.youtube.com')
		.post('/youtubei/v1/player')
		.query({ key: API_KEY })
		.reply(200, body);

beforeAll(() => {
	nock.disableNetConnect();
});

afterEach(() => {
	nock.cleanAll();
});

afterAll(() => {
	nock.enableNetConnect();
});

describe('inspectPlayerResponse', () => {
	it('should return player inspection details successfully', async () => {
		mockWatchPage();
		mockPlayer(loadJsonFixture('player-success.json'));

		const result = await inspectPlayerResponse(VIDEO_ID);

		expect(result).toEqual({
			videoId: VIDEO_ID,
			playabilityStatus: 'OK',
			captionTracks: [
				{
					languageCode: 'en',
					name: '[en]',
					kind: 'unknown',
					baseUrl:
						'https://www.youtube.com/api/timedtext?lang=en&v=TESTVIDEOID',
				},
			],
			translationLanguages: [],
			hasAutoGeneratedCaptions: false,
		});
	});

	it('should handle errors gracefully', async () => {
		mockWatchPage();
		nock('https://www.youtube.com')
			.post('/youtubei/v1/player')
			.query({ key: API_KEY })
			.reply(500);

		const result = await inspectPlayerResponse(VIDEO_ID);

		expect(result.playabilityStatus).toBe('ERROR');
		expect(result.captionTracks).toEqual([]);
		expect(result.error).toBeDefined();
	});
});

describe('inspectPlayerResponseDebug', () => {
	it('should return verbose debug information', async () => {
		mockWatchPage();
		mockPlayer(loadJsonFixture('player-success.json'));

		const result = await inspectPlayerResponseDebug(VIDEO_ID, undefined, {
			includeRawData: true,
		});

		expect(result.videoId).toBe(VIDEO_ID);
		expect(result.playabilityStatus).toBe('OK');
		expect(result.debug).toBeDefined();
		expect(result.debug.steps).toHaveLength(3);
		expect(result.debug.steps[0]).toEqual({
			step: 'Extract Video ID',
			status: 'success',
			details: { videoId: VIDEO_ID },
		});
		expect(result.debug.watchPageHtml?.apiKeyFound).toBe(true);
		expect(result.debug.watchPageHtml?.content).toContain('INNERTUBE_API_KEY');
		expect(result.debug.playerResponse?.hasCaptions).toBe(true);
		expect(result.debug.playerResponse?.content).toBeDefined();
	});

	it('should capture step failures', async () => {
		mockWatchPage();
		nock('https://www.youtube.com')
			.post('/youtubei/v1/player')
			.query({ key: API_KEY })
			.reply(500);

		const result = await inspectPlayerResponseDebug(VIDEO_ID);

		expect(result.playabilityStatus).toBe('ERROR');
		expect(result.debug.steps.some((step) => step.status === 'error')).toBe(
			true,
		);
	});
});
